### PR TITLE
Console updates

### PR DESCRIPTION
**Pull request by flukeout**
Quite a few changes here including:

* New & updated styling
  * "X" icon for closing the console
  * "Open Console" tab now lights up blue when you have unseen console logs
  * Finished dark & light themes
  * New log entries have a blue glow when they get added
  * Updated vertical resizer styling
* Finished localization
* Objects now display as stringified JSON, so no more ``[Object object]`` in the log

Give it a try @raygervais - and merge if everything seems good. We'll get a final code review form Gideon on the PR against our brackets branch.

### CODE REVIEW

**Comment by raygervais** [comment]
@flukeout, looked over all the code & aside from a few spacing inconsistencies I'd happily merge this to my PR. One issue that I've noticed that perhaps revolves around my machine alone, is that though I can run my PR's brackets, for some reason I cannot run yours. 

After `npm start`, it seems to hang on `dist/config.json`. Perhaps a fluke? :D

**Comment by flukeout** [comment]
Oh shoot - weird. Does it give any indication of what's wrong with config.json?

**Comment by raygervais** [comment]
The backend itself is stuck on `[Sat May 06 2017 19:27:57 GMT-0400 (EDT)] "GET /dist/config.json" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"`

On yours, I see the following console statements:
image

Whereas on the original branch:
image

Perhaps the `i is defined` error being the cause? I don't see where it would affect the `config.json` though.

**Comment by raygervais** [comment]
I managed to test your work by copying the changes themselves to my repo, and everything seems to work so far. Merging.

**Comment by flukeout** [comment]
Okay, cool - I'll test the updated PR against brackets to make sure everything worked out! Thanks!

**Pull request merged**
